/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "Test_Designs/num_5.v:6" *)
module num_5(A, B, sel, Y);
  wire _0_;
  wire _1_;
  (* src = "Test_Designs/num_5.v:6" *)
  input A;
  (* src = "Test_Designs/num_5.v:6" *)
  input B;
  (* src = "Test_Designs/num_5.v:6" *)
  output Y;
  (* src = "Test_Designs/num_5.v:6" *)
  input sel;
  INVX1 _2_ (
    .A(B),
    .Y(_0_)
  );
  NAND2X1 _3_ (
    .A(A),
    .B(sel),
    .Y(_1_)
  );
  OAI21X1 _4_ (
    .A(sel),
    .B(_0_),
    .C(_1_),
    .Y(Y)
  );
endmodule
