/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "Test_Designs/num_3.v:6" *)
module num_3(A, B, C, D, Y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "Test_Designs/num_3.v:6" *)
  input A;
  (* src = "Test_Designs/num_3.v:6" *)
  input B;
  (* src = "Test_Designs/num_3.v:6" *)
  input C;
  (* src = "Test_Designs/num_3.v:6" *)
  input D;
  (* src = "Test_Designs/num_3.v:6" *)
  output Y;
  NAND2X1 _08_ (
    .A(A),
    .B(B),
    .Y(_04_)
  );
  OR2X2 _09_ (
    .A(C),
    .B(D),
    .Y(_05_)
  );
  NAND2X1 _10_ (
    .A(C),
    .B(D),
    .Y(_06_)
  );
  NAND3X1 _11_ (
    .A(_04_),
    .B(_06_),
    .C(_05_),
    .Y(_07_)
  );
  AND2X2 _12_ (
    .A(A),
    .B(B),
    .Y(_00_)
  );
  NOR2X1 _13_ (
    .A(C),
    .B(D),
    .Y(_01_)
  );
  AND2X2 _14_ (
    .A(C),
    .B(D),
    .Y(_02_)
  );
  OAI21X1 _15_ (
    .A(_01_),
    .B(_02_),
    .C(_00_),
    .Y(_03_)
  );
  NAND2X1 _16_ (
    .A(_03_),
    .B(_07_),
    .Y(Y)
  );
endmodule
