/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "Test_Designs/num_8.v:6" *)
module num_8(a, b, c);
  (* src = "Test_Designs/num_8.v:6" *)
  input a;
  (* src = "Test_Designs/num_8.v:6" *)
  input b;
  (* src = "Test_Designs/num_8.v:6" *)
  output c;
  OR2X2 _0_ (
    .A(b),
    .B(a),
    .Y(c)
  );
endmodule
