/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "Test_Designs/num_4.v:6" *)
module num_4(A, B, C, D, Y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "Test_Designs/num_4.v:6" *)
  input A;
  (* src = "Test_Designs/num_4.v:6" *)
  input B;
  (* src = "Test_Designs/num_4.v:6" *)
  input C;
  (* src = "Test_Designs/num_4.v:6" *)
  input D;
  (* src = "Test_Designs/num_4.v:6" *)
  output Y;
  INVX1 _05_ (
    .A(C),
    .Y(_01_)
  );
  NAND2X1 _06_ (
    .A(D),
    .B(_01_),
    .Y(_02_)
  );
  NAND2X1 _07_ (
    .A(A),
    .B(B),
    .Y(_03_)
  );
  INVX1 _08_ (
    .A(D),
    .Y(_04_)
  );
  NAND2X1 _09_ (
    .A(C),
    .B(_04_),
    .Y(_00_)
  );
  NAND3X1 _10_ (
    .A(_03_),
    .B(_02_),
    .C(_00_),
    .Y(Y)
  );
endmodule
