/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "Test_Designs/num_10.v:6" *)
module num_8(clk, d, cout);
  (* src = "Test_Designs/num_10.v:6" *)
  input clk;
  (* src = "Test_Designs/num_10.v:6" *)
  output cout;
  (* src = "Test_Designs/num_10.v:6" *)
  input d;
  DFFPOSX1 _0_ (
    .CLK(clk),
    .D(d),
    .Q(cout)
  );
endmodule
